package com.sshtools.javardp.layers.nla;

public interface NTLM {
	
	int NTLMSSP_NEGOTIATE_56 = 1 << 31;
	int NTLMSSP_NEGOTIATE_KEY_EXCH = 1 << 30;
	int NTLMSSP_NEGOTIATE_128 = 1 << 29;
	int NTLMSSP_RESERVED_1 = 1 << 28;
	int NTLMSSP_RESERVED_2 = 1 << 27;
	int NTLMSSP_RESERVED_3 = 1 << 26;
	int NTLMSSP_NEGOTIATE_VERSION = 1 << 25;
	int NTLMSSP_RESERVED_4 = 1 << 24;
	int NTLMSSP_NEGOTIATE_TARGET_INFO = 1 << 23;
	int NTLMSSP_REQUEST_NON_NT_SESSION_KEY = 1 << 22;
	int NTLMSSP_RESERVED_5 = 1 << 21;
	int NTLMSSP_NEGOTIATE_IDENTIFY = 1 << 20;
	int NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY = 1 << 19;
	int NTLMSSP_RESERVED_6 = 1 << 18;
	int NTLMSSP_TARGET_TYPE_SERVER = 1 << 17;
	int NTLMSSP_TARGET_TYPE_DOMAIN = 1 << 16;
	int NTLMSSP_NEGOTIATE_ALWAYS_SIGN = 1 << 15;
	int NTLMSSP_RESERVED_7 = 1 << 14;
	int NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED = 1 << 13;
	int NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED = 1 << 12;
	int NTLMSSP_ANONYMOUS = 1 << 11;
	int NTLMSSP_RESERVED_8 = 1 << 10;
	int NTLMSSP_NEGOTIATE_NTLM = 1 << 9;
	int NTLMSSP_RESERVED_9 = 1 << 8;
	int NTLMSSP_NEGOTIATE_LM_KEY = 1 << 7;
	int NTLMSSP_NEGOTIATE_DATAGRAM = 1 << 6;
	int NTLMSSP_NEGOTIATE_SEAL = 1 << 5;
	int NTLMSSP_NEGOTIATE_SIGN = 1 << 4;
	int NTLMSSP_RESERVED_10 = 1 << 3;
	int NTLMSSP_REQUEST_TARGET = 1 << 2;
	int NTLM_NEGOTIATE_OEM = 1 << 1;
	int NTLMSSP_NEGOTIATE_UNICODE = 1;
	
	byte[] SIG = new byte[] { (byte) 'N', (byte) 'T', (byte) 'L', (byte) 'M', (byte) 'S', (byte) 'S', (byte) 'P', (byte) 0 };
	byte[] NULL_BYTES = new byte[0];
}
